# Generated by Django 3.1.5 on 2021-05-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=30)),
                ('price', models.IntegerField(default=30)),
                ('stripe_plan_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(default=12345, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(default=12345, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.membership'),
        ),
    ]
