# Generated by Django 3.1.5 on 2021-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamname',
            name='abbreviation',
            field=models.CharField(max_length=100),
        ),
    ]
