# Generated by Django 3.1.5 on 2021-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(max_length=20, to='management.Team'),
        ),
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
