# Generated by Django 3.1.5 on 2021-02-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210214_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default='NCAAB', on_delete=django.db.models.deletion.CASCADE, to='management.league'),
        ),
    ]
