# Generated by Django 3.1.5 on 2021-02-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210216_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(choices=[('MLB', 'MLB'), ('NBA', 'NBA'), ('NCAAB', 'NCAAB'), ('NFL', 'NFL')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default='NCAAB', on_delete=django.db.models.deletion.CASCADE, to='management.league', to_field='name', unique=True),
        ),
    ]
