# Generated by Django 3.1.5 on 2021-03-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210216_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('points_for', models.IntegerField()),
                ('points_against', models.IntegerField()),
                ('field_goals', models.IntegerField()),
                ('field_goal_attempts', models.IntegerField()),
                ('three_pointers', models.IntegerField()),
                ('three_point_attempts', models.IntegerField()),
                ('free_throws', models.IntegerField()),
                ('free_throw_attempts', models.IntegerField()),
                ('opp_free_throw_attempts', models.IntegerField()),
                ('offensive_rebounds', models.IntegerField()),
                ('opp_offensive_rebounds', models.IntegerField()),
                ('opp_defensive_rebounds', models.IntegerField()),
                ('opp_field_goal_percentage', models.FloatField()),
                ('defensive_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('personal_fouls', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamName',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teamname'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season'),
        ),
    ]
