# Generated by Django 3.1.5 on 2021-03-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210329_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='BasketballTeamStats',
        ),
        migrations.CreateModel(
            name='BaseballTeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('home_record', models.CharField(max_length=10)),
                ('away_record', models.CharField(max_length=10)),
                ('runs_allowed_per_games', models.FloatField()),
                ('batting_average', models.FloatField()),
                ('earned_runs_against', models.FloatField()),
                ('hits', models.IntegerField()),
                ('hits_allowed', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('home_runs_against', models.IntegerField()),
                ('record_vs_lefties', models.CharField(max_length=20)),
                ('record_vs_righties', models.CharField(max_length=20)),
                ('record_vs_500_teams', models.CharField(max_length=20)),
                ('record_vs_teams_under_500', models.CharField(max_length=20)),
                ('on_base_percentage', models.FloatField()),
                ('run_difference', models.FloatField()),
                ('streak', models.CharField(max_length=20)),
                ('total_runs', models.IntegerField()),
                ('last_ten', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teamname')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season')),
            ],
        ),
    ]
