# Generated by Django 3.1.5 on 2021-04-02 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20210331_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='away_record',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='earned_runs_against',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='home_record',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='last_ten',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='on_base_percentage',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='record_vs_500_teams',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='record_vs_lefties',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='record_vs_righties',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='record_vs_teams_under_500',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='run_difference',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='runs_allowed_per_games',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='total_runs',
        ),
        migrations.RemoveField(
            model_name='baseballteamstats',
            name='wins',
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='at_bats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='bullpen_innings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='bullpen_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='loss_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='loss_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='runs_against_first_five',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='runs_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='runs_first_five',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='strikeouts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='win_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballteamstats',
            name='win_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='hits_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='home_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='home_runs_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='name',
            field=models.ForeignKey(choices=[('Los Angeles Dodgers', 'Los Angeles Dodgers'), ('Tampa Bay Rays', 'Tampa Bay Rays'), ('San Diego Padres', 'San Diego Padres'), ('Minnesota Twins', 'Minnesota Twins'), ('Oakland Athletics', 'Oakland Athletics'), ('Atlanta Braves', 'Atlanta Braves'), ('Chicago White Sox', 'Chicago White Sox'), ('Cleveland Indians', 'Cleveland Indians'), ('Chicago Cubs', 'Chicago Cubs'), ('New York Yankees', 'New York Yankees'), ('Toronto Blue Jays', 'Toronto Blue Jays'), ('St. Louis Cardinals', 'St. Louis Cardinals'), ('Miami Marlins', 'Miami Marlins'), ('Cincinnati Reds', 'Cincinnati Reds'), ('Houston Astros', 'Houston Astros'), ('San Francisco Giants', 'San Francisco Giants'), ('Milwaukee Brewers', 'Milwaukee Brewers'), ('Philadelphia Phillies', 'Philadelphia Phillies'), ('Seattle Mariners', 'Seattle Mariners'), ('New York Mets', 'New York Mets'), ('Colorado Rockies', 'Colorado Rockies'), ('Kansas City Royals', 'Kansas City Royals'), ('Los Angeles Angels', 'Los Angeles Angels'), ('Washington Nationals', 'Washington Nationals'), ('Baltimore Orioles', 'Baltimore Orioles'), ('Arizona Diamondbacks', 'Arizona Diamondbacks'), ('Boston Red Sox', 'Boston Red Sox'), ('Detroit Tigers', 'Detroit Tigers'), ('Texas Rangers', 'Texas Rangers'), ('Pittsburgh Pirates', 'Pittsburgh Pirates')], on_delete=django.db.models.deletion.CASCADE, to='management.teamname'),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='season',
            field=models.ForeignKey(choices=[('MLB2021', 'MLB2021')], default='MLB2021', on_delete=django.db.models.deletion.CASCADE, to='management.season'),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='blocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='defensive_rebounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='field_goal_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='field_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='free_throw_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='free_throws',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='games_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='offensive_rebounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='opp_defensive_rebounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='opp_field_goal_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='opp_free_throw_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='opp_offensive_rebounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='personal_fouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='points_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='points_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='steals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='three_point_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='three_pointers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballteamstats',
            name='turnovers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StartingPitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('innings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('runs', models.IntegerField()),
                ('runs_first_five', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('walks', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('season', models.ForeignKey(choices=[('MLB2021', 'MLB2021')], default='MLB2021', on_delete=django.db.models.deletion.CASCADE, to='management.season')),
                ('team', models.ForeignKey(choices=[('Los Angeles Dodgers', 'Los Angeles Dodgers'), ('Tampa Bay Rays', 'Tampa Bay Rays'), ('San Diego Padres', 'San Diego Padres'), ('Minnesota Twins', 'Minnesota Twins'), ('Oakland Athletics', 'Oakland Athletics'), ('Atlanta Braves', 'Atlanta Braves'), ('Chicago White Sox', 'Chicago White Sox'), ('Cleveland Indians', 'Cleveland Indians'), ('Chicago Cubs', 'Chicago Cubs'), ('New York Yankees', 'New York Yankees'), ('Toronto Blue Jays', 'Toronto Blue Jays'), ('St. Louis Cardinals', 'St. Louis Cardinals'), ('Miami Marlins', 'Miami Marlins'), ('Cincinnati Reds', 'Cincinnati Reds'), ('Houston Astros', 'Houston Astros'), ('San Francisco Giants', 'San Francisco Giants'), ('Milwaukee Brewers', 'Milwaukee Brewers'), ('Philadelphia Phillies', 'Philadelphia Phillies'), ('Seattle Mariners', 'Seattle Mariners'), ('New York Mets', 'New York Mets'), ('Colorado Rockies', 'Colorado Rockies'), ('Kansas City Royals', 'Kansas City Royals'), ('Los Angeles Angels', 'Los Angeles Angels'), ('Washington Nationals', 'Washington Nationals'), ('Baltimore Orioles', 'Baltimore Orioles'), ('Arizona Diamondbacks', 'Arizona Diamondbacks'), ('Boston Red Sox', 'Boston Red Sox'), ('Detroit Tigers', 'Detroit Tigers'), ('Texas Rangers', 'Texas Rangers'), ('Pittsburgh Pirates', 'Pittsburgh Pirates')], on_delete=django.db.models.deletion.CASCADE, to='management.teamname')),
            ],
        ),
    ]
