# Generated by Django 3.1.5 on 2021-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210402_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballteamstats',
            name='bullpen_innings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='home_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='innings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='runs_first_five',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='strikeouts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='walks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
