# Generated by Django 3.1.5 on 2021-04-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210403_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseballteamstats',
            old_name='runs_against_first_five',
            new_name='runs_allowed_first_five',
        ),
    ]
