# Generated by Django 3.1.5 on 2021-04-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210403_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballteamstats',
            name='opponent_at_bats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teamname'),
        ),
        migrations.AlterField(
            model_name='baseballteamstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season'),
        ),
    ]
