# Generated by Django 3.1.5 on 2021-04-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210403_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseballTeamStats',
            new_name='BaseballGame',
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.season'),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teamname'),
        ),
    ]
