# Generated by Django 3.1.5 on 2021-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20210403_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballgame',
            name='nickname',
            field=models.CharField(choices=[('Rays', 'Rays'), ('Orioles', 'Orioles'), ('BlueJays', 'BlueJays'), ('RedSox', 'RedSox'), ('Yankees', 'Yankees'), ('Tigers', 'Tigers'), ('Royals', 'Royals'), ('WhiteSox', 'WhiteSox'), ('Indians', 'Indians'), ('Twins', 'Twins'), ('Astros', 'Astros'), ('Angels', 'Angels'), ('Mariners', 'Mariners'), ('Rangers', 'Rangers'), ('Athletics', 'Athletics'), ('Phillies', 'Phillies'), ('Mets', 'Mets'), ('Nationals', 'Nationals'), ('Braves', 'Braves'), ('Marlins', 'Marlins'), ('Brewers', 'Brewers'), ('Pirates', 'Pirates'), ('Cardinals', 'Cardinals'), ('Cubs', 'Cubs'), ('Reds', 'Reds')], default='MLB', max_length=20),
        ),
    ]
