# Generated by Django 3.1.5 on 2021-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20210404_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballgame',
            name='opponent',
            field=models.CharField(default='MLB', max_length=50),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='at_bats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='bullpen_inning_thirds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='bullpen_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='hits_allowed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='home_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='home_runs_against',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='loss_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='loss_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='nickname',
            field=models.CharField(choices=[('Angels', 'Angels'), ('Astros', 'Astros'), ('Athletics', 'Athletics'), ('BlueJays', 'BlueJays'), ('Braves', 'Braves'), ('Brewers', 'Brewers'), ('Cardinals', 'Cardinals'), ('Cubs', 'Cubs'), ('Diamondbacks', 'Diamondbacks'), ('Dodgers', 'Dodgers'), ('Giants', 'Giants'), ('Indians', 'Indians'), ('Mariners', 'Mariners'), ('Marlins', 'Marlins'), ('Mets', 'Mets'), ('Nationals', 'Nationals'), ('Orioles', 'Orioles'), ('Padres', 'Padres'), ('Phillies', 'Phillies'), ('Pirates', 'Pirates'), ('Rangers', 'Rangers'), ('Rays', 'Rays'), ('Reds', 'Reds'), ('RedSox', 'RedSox'), ('Rockies', 'Rockies'), ('Royals', 'Royals'), ('Tigers', 'Tigers'), ('Twins', 'Twins'), ('WhiteSox', 'WhiteSox'), ('Yankees', 'Yankees')], default='MLB', max_length=20),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='opponent_at_bats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='runs_allowed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='runs_allowed_first_five',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='runs_first_five',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='strikeouts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='win_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='win_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='home_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='inning_thirds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='runs_first_five',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='strikeouts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='walks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
