# Generated by Django 3.1.5 on 2021-04-14 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20210412_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlbtoday',
            old_name='schedule',
            new_name='gamedate',
        ),
        migrations.AddField(
            model_name='mlbtoday',
            name='away_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlbtoday',
            name='home_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlbtoday',
            name='status',
            field=models.CharField(default='final', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 13)),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 13)),
        ),
    ]
