# Generated by Django 3.1.5 on 2021-04-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20210415_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbtoday',
            name='away_moneyline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='away_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='away_spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='home_moneyline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='home_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='home_spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='over_odds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbtoday',
            name='under_odds',
            field=models.IntegerField(default=0),
        ),
    ]
