# Generated by Django 3.1.5 on 2021-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20210415_0557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseballGame',
            new_name='MLBGame',
        ),
        migrations.RenameModel(
            old_name='MLBToday',
            new_name='MLBGameLine',
        ),
    ]
