# Generated by Django 3.1.5 on 2021-04-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20210416_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='gameday',
            field=models.DateTimeField(null=True),
        ),
    ]
