# Generated by Django 3.1.5 on 2021-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_mlbgameline_gameday'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='league',
            field=models.CharField(default='MLB', max_length=10),
        ),
    ]
