# Generated by Django 3.1.5 on 2021-04-17 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_mlbgameline_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbgame',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='gamedate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='league',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
    ]
