# Generated by Django 3.1.5 on 2021-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20210417_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbgameline',
            name='gamedate',
            field=models.DateTimeField(),
        ),
    ]
