# Generated by Django 3.1.5 on 2021-04-18 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_auto_20210417_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbgame',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='away_spread',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='home_spread',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
    ]
