# Generated by Django 3.1.5 on 2021-04-24 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20210423_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlbgameline',
            old_name='game_id',
            new_name='gameID',
        ),
        migrations.AlterField(
            model_name='mlbgame',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 23)),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 23)),
        ),
    ]
