# Generated by Django 3.1.5 on 2021-04-26 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20210424_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='away_starter_hand',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='mlbgameline',
            name='away_starter_ip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbgameline',
            name='home_starter_hand',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='mlbgameline',
            name='home_starter_ip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlbgame',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 25)),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 25)),
        ),
    ]
