# Generated by Django 3.1.5 on 2021-04-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20210426_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbgame',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='away_starter_ip',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mlbgameline',
            name='home_starter_ip',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='startingpitcher',
            name='date',
            field=models.DateField(),
        ),
    ]
