# Generated by Django 3.1.5 on 2021-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20210426_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='current_inning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamname',
            name='twitter_id',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
