# Generated by Django 3.1.5 on 2021-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_auto_20210428_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='away_starter_whip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='mlbgameline',
            name='home_starter_whip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
