# Generated by Django 3.1.5 on 2021-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_auto_20210512_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgameline',
            name='away_starts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlbgameline',
            name='home_starts',
            field=models.IntegerField(default=0),
        ),
    ]
